# Generated by Django 4.1.4 on 2022-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="logos/")),
                ("description", models.TextField(blank=True)),
                ("partner_tel", models.CharField(max_length=255)),
                ("partner_email", models.EmailField(max_length=254)),
                ("partner_person", models.CharField(max_length=255)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_start_working", models.DateField()),
                ("time_expires", models.DateField()),
                ("is_working", models.BooleanField(default=False)),
            ],
        ),
    ]
