# Generated by Django 4.1.4 on 2023-02-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jaimain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('tel_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=255, verbose_name='Город проживания')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('partner', 'firstname', 'lastname', 'birthdate')},
            },
        ),
        migrations.RemoveField(
            model_name='jaiuser',
            name='is_costumer',
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_amount', models.IntegerField(verbose_name='Количество бонусов')),
                ('receive_or_spend', models.CharField(max_length=10, verbose_name='Списание или начисление')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.customer', verbose_name='Покупатель')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.partner', verbose_name='Партнер')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.sellreceipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Бонусы',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='BaseLoyaltySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_achieve', models.IntegerField(verbose_name='% начисляемых бонусов')),
                ('points_spend', models.IntegerField(verbose_name='% стоимости товара для оплаты бонусами')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.partner', unique=True, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Базовая система лояльности',
                'verbose_name_plural': 'Базовые системы лояльности',
            },
        ),
        migrations.AddField(
            model_name='sellreceipt',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Jaimain.customer', verbose_name='Клиент'),
        ),
    ]
