# Generated by Django 4.1.4 on 2022-12-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jaimain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaiuser',
            name='is_costumer',
            field=models.BooleanField(default=False, verbose_name='Является покупателем'),
        ),
        migrations.AddField(
            model_name='jaiuser',
            name='tel_number',
            field=models.CharField(default=123, max_length=255, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jaiuser',
            name='partner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Jaimain.partner', verbose_name='Партнер'),
        ),
    ]
