# Generated by Django 4.1.4 on 2023-01-07 11:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Jaimain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование свойства')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jaimain.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Свойство товара',
                'verbose_name_plural': 'Свойства товаров',
                'unique_together': {('partner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='product_images/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('producer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaimain.productcategory', verbose_name='Категория')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jaimain.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'unique_together': {('partner', 'identifier', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductPropertyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jaimain.sku', verbose_name='SKU')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jaimain.productproperty', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Связь свойства и товара',
                'verbose_name_plural': 'Связи свойств и товаров',
                'unique_together': {('product', 'property')},
            },
        ),
    ]
