# Generated by Django 4.1.4 on 2022-12-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jaimain', '0002_jaiuser_is_costumer_jaiuser_tel_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование торговой точки')),
                ('location', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_working', models.BooleanField(default=True, verbose_name='Активность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('partner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Jaimain.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'ordering': ['id'],
            },
        ),
    ]
